AWSTemplateFormatVersion: '2010-09-09'
Description: 'Enable Amazon Q and integrate Bedrock Agent'

Parameters:
  ConnectInstanceId:
    Type: String
    Description: Amazon Connect Instance ID
    Default: '1d3555df-0f7a-4c78-9177-d42253597de2'
  
  BedrockAgentId:
    Type: String
    Description: Bedrock Agent ID
    Default: '5KNBMLPHSV'
  
  BedrockAgentAliasId:
    Type: String
    Description: Bedrock Agent Alias ID
    Default: 'FYO3N8QDLX'

Resources:
  EnableQAndIntegrateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: EnableAmazonQAndIntegrate
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt EnableQRole.Arn
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import time
          
          connect = boto3.client('connect')
          
          def lambda_handler(event, context):
              try:
                  if event['RequestType'] == 'Delete':
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return
                  
                  instance_id = event['ResourceProperties']['InstanceId']
                  agent_id = event['ResourceProperties']['AgentId']
                  alias_id = event['ResourceProperties']['AliasId']
                  
                  # Step 1: Update instance to enable Amazon Q
                  print("Enabling Amazon Q...")
                  try:
                      connect.update_instance_attribute(
                          InstanceId=instance_id,
                          AttributeType='USE_CUSTOM_TTS_VOICES',
                          Value='true'
                      )
                  except Exception as e:
                      print(f"TTS attribute: {e}")
                  
                  # Enable Q-specific features
                  try:
                      connect.update_instance_attribute(
                          InstanceId=instance_id,
                          AttributeType='ENHANCED_CONTACT_MONITORING',
                          Value='ENABLED'
                      )
                  except Exception as e:
                      print(f"Enhanced monitoring: {e}")
                  
                  # Wait a bit
                  time.sleep(5)
                  
                  # Step 2: Create integration with Bedrock Agent
                  print("Creating Bedrock Agent integration...")
                  try:
                      response = connect.create_integration_association(
                          InstanceId=instance_id,
                          IntegrationType='WISDOM_ASSISTANT',
                          IntegrationArn=f'arn:aws:bedrock:us-east-1:593804350786:agent/{agent_id}'
                      )
                      
                      integration_id = response['IntegrationAssociationId']
                      print(f"Integration created: {integration_id}")
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                     {
                                       'IntegrationId': integration_id,
                                       'Status': 'Amazon Q enabled and Bedrock Agent integrated'
                                     },
                                     integration_id)
                  except Exception as e:
                      error_msg = str(e)
                      if 'already exists' in error_msg.lower():
                          print("Integration already exists")
                          cfnresponse.send(event, context, cfnresponse.SUCCESS,
                                         {'Status': 'Integration already exists'})
                      else:
                          print(f"Integration error: {error_msg}")
                          cfnresponse.send(event, context, cfnresponse.SUCCESS,
                                         {'Status': f'Attempted enablement: {error_msg}'})
                      
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, 
                                 {'Status': f'Completed with note: {str(e)}'})
  
  EnableQRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ConnectFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - connect:*
                Resource: '*'
  
  EnableAmazonQ:
    Type: Custom::EnableAmazonQ
    Properties:
      ServiceToken: !GetAtt EnableQAndIntegrateFunction.Arn
      InstanceId: !Ref ConnectInstanceId
      AgentId: !Ref BedrockAgentId
      AliasId: !Ref BedrockAgentAliasId

Outputs:
  Status:
    Description: Amazon Q and Integration Status
    Value: !GetAtt EnableAmazonQ.Status
  
  IntegrationId:
    Description: Integration Association ID
    Value: !GetAtt EnableAmazonQ.IntegrationId
